{{- $fullName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certArn }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Values.environment }}.{{ .Values.ingress.domain }}
    alb.ingress.kubernetes.io/security-groups: "main-vpc-private-http,main-vpc-private-https"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: Name={{ .Release.Name }},Service={{ .Release.Name }},Environment={{ .Values.environment }},Owner={{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
